name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brucearctor/ruff@v0.0.009
        with:
          version: 0.0.249
          options: --select ANN